services:
  - type: web
    name: Slot-Machine-Java-Backend
    env: java
    plan: free
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromEnvVar: SPRING_DATASOURCE_URL
      - key: SPRING_DATASOURCE_USERNAME
        fromEnvVar: SPRING_DATASOURCE_USERNAME
      - key: SPRING_DATASOURCE_PASSWORD
        fromEnvVar: SPRING_DATASOURCE_PASSWORD
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk
